### ISSUE TITLE
"Provide a menu link" functionality messed up for new/custom menus

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/menu_views#3]
When this module is enabled, the "Provide a menu link" functionality is messed up if you are not using the Primary Navigation on a content type.

For example, create a new menu and create/edit a content type so that it only has menu access for this new menu.

<img width="952" alt="screen shot 2017-08-09 at 11 28 38 am" src="https://user-images.githubusercontent.com/871421/29132467-f00bc740-7cf5-11e7-9bc8-a4efdd63ce73.png">

When creating content of this type, the menu option still shows the default menu (although it won't actually save the menu item to this menu, likely due to permissions).

<img width="937" alt="screen shot 2017-08-09 at 11 30 37 am" src="https://user-images.githubusercontent.com/871421/29132563-3640d552-7cf6-11e7-8be3-90f77e069004.png">

Unsure at this point if it is related to #1 .

**Comment by serundeputy** [comment]
@laryn you need to fix this: https://github.com/laryn/menu_views/blob/1.x-1.x/menu_views.admin.inc#L662

It is using `variable_get` so you'll need to have config replacement for that.

**Comment by laryn** [comment]
@serundeputy Working through these now. Interestingly, that variable you link to (`menu_override_parent_selector`) has been [deleted in Backdrop](https://api.backdropcms.org/node/26868)...

**Comment by laryn** [comment]
Seems to be all worked out in testing with the latest commit.
