### ISSUE TITLE
Error: Call to a member function pre_render() on null in view->render() (line 1245 of .../view.inc).

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/menu_views#7]
Enabling the module and attaching a test view block breaks my test Backdrop website giving:

```
Error: Call to a member function pre_render() on null in view->render() (line 1245 of /var/www/docroot/core/modules/views/includes/view.inc).
```

**Comment by alanmels** [comment]
Most probably, this one is the consequence of https://github.com/backdrop-contrib/menu_views/issues/8

**Comment by alanmels** [comment]
Interestingly, the following `if condition` is never satisfied, so the inner code is never triggered and that could be culprit:

```
function _menu_views_replace_menu_item($element) {
  $build = array();
  $item = _menu_views_get_item($element);
  _menu_views_tokenize($item);
  if ($item['type'] == 'view' && $item['view']['name'] && $item['view']['display']) {
    sdpm('bingo');
```

**Comment by alanmels** [comment]
The module works as expected if the following lines in `/var/www/docroot/core/modules/views/includes/view.inc`:

```
1256 $exposed_form->pre_render($this->result);
1313 $exposed_form->post_render($this->display_handler->output);
```
are commented out. If this issue can not be fixed within the module, then probably we have to request the change in the `views` module.

**Comment by alanmels** [comment]
There is a similar error report on https://www.drupal.org/project/views/issues/2975895, which unfortunately was never fixed, probably because the reporter fixed their problem elsewhere and not in views module.

**Comment by alanmels** [comment]
The whole thing was about my block view to have `exposed form`, so without it, it works as expected. However, I believe the reported error still needs to be addressed for views blocks created with `Create exposed form block:` set to "Yes" as shown:

![Screenshot from 2021-04-22 02-42-49](https://user-images.githubusercontent.com/56604405/115684437-963a2b00-a314-11eb-8ddd-92ecfeae8384.png)

**Comment by laryn** [comment]
@alanmels Thanks for reporting -- I agree, this should be addressed. Any chance you can provide a PR for me to review? 😇

**Comment by alanmels** [comment]
@laryn, we've moved on by using an alternative method - https://github.com/backdrop-contrib/menu_attach_block - so unfortunately I won't have time to troubleshoot this.

**Comment by laryn** [comment]
Got it -- thanks.

**Comment by laryn** [comment]
@alanmels I know you've moved on from this one but I can't replicate the issue. I have tested the following: 

- created a block display and added it to the menu (works)
- added an exposed filter on the view with Ajax enabled (works)
- added a page display with an exposed filter and set the exposed filter as a block (works)

I'll close this for now but if someone runs into something similar and can provide steps to reproduce let's reopen it.
