### ISSUE TITLE
Typo in config setting name for Views field wrapper elements.

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/menu_views#8]
When selecting a view, it is giving:
```
Warning: Invalid argument supplied for foreach() in form_select_options() (line 2873 of /var/www/docroot/core/includes/form.inc).
```
![Screenshot from 2021-04-21 15-40-52](https://user-images.githubusercontent.com/56604405/115624647-226a3500-a2b8-11eb-982e-e21116c10cb9.png)

**Comment by alanmels** [comment]
The [line 487](https://github.com/backdrop-contrib/menu_views/blob/aebe8bec0cbfe4818131d1b6d4b1f76a63adeff7/menu_views.admin.inc#L497) looks like:
```
'#options' => config_get('views.settings','views_field_rewrite_elements'),
```
but then the module does not have any configuration files. So the patch re-instates the options present in Drupal 7 version of the module.

**Comment by laryn** [comment]
Thank you @alanmels -- I've fixed this in a slightly different way but appreciate you pinpointing this issue and filing a fix for it.
